name: app_smart_network
description: "A smart Flutter network package with built-in error handling, configurable retry, optional SSL certificate pinning (Android/iOS), and multilingual error messages (en/ar)."
version: 2.1.0
repository: https://github.com/devmuhammadreda/app_smart_network
homepage: https://github.com/devmuhammadreda/app_smart_network

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  connectivity_plus: ^7.3.1
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^7.0.1
  http_certificate_pinning: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
